name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend/LandOfRex
          npm install

      - name: Build React app
        run: |
          cd frontend/LandOfRex
          npm run build

      - name: Copy config to dist
        run: |
          cp frontend/LandOfRex/public/staticwebapp.config.json frontend/LandOfRex/dist/

      - name: List dist files (debug)
        run: |
          ls -R frontend/LandOfRex/dist

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_GROUND_01B32B300 }}
          action: "upload"
          app_location: "frontend/LandOfRex"
          output_location: "dist"
