name: React Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend/LandOfRex

      - name: Build React
        run: npm run build
        working-directory: ./frontend/LandOfRex

      - name: Remove old build on VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          # build 디렉토리 자체를 삭제하고 다시 만듭니다.
          script: |
            rm -rf /home/azureuser/landofrex-react/build 
            mkdir -p /home/azureuser/landofrex-react/build 

      - name: Copy new build to VM 🚀
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          # 1. source에 /*를 추가하여 build 폴더의 내용물 전체를 지정
          source: "frontend/LandOfRex/build/*" 
          # 2. target은 내용물이 복사되어 들어갈 build 폴더까지 지정
          target: "/home/azureuser/landofrex-react/build/"
          
      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: sudo systemctl reload nginx
